import { HintedString } from './helpers';
import { BuildEnvironmentOptions, LogLevel, ServerOptions } from 'vite';

export type CLIBuildMode = HintedString<'production' | 'development'>;

export interface GlobalCLIOptions {
  '--'?: string[];
  'c'?: boolean | string;
  'config'?: string;
  'base'?: string;
  'l'?: LogLevel;
  'logLevel'?: LogLevel;
  'clearScreen'?: boolean;
  'configLoader'?: 'bundle' | 'runner' | 'native';
  'd'?: boolean | string;
  'debug'?: boolean | string;
  'f'?: string;
  'filter'?: string;
  'm'?: string;
  'mode'?: CLIBuildMode;
  'force'?: boolean;
  'w'?: boolean;
}

export interface ServeCommandCLIOptions {
  /**
   * Enable HTTPS serve using a self-signed certificate generated by @vitejs/plugin-basic-ssl.
   * This is useful for local development of micro-frontends that require HTTPS.
   */
  https?: boolean;
}

export interface PreviewCommandCLIOptions {
  host?: string | boolean;
  port?: number;
  open?: boolean | string;
  strictPort?: boolean;
  outDir?: string;
}

export interface BuilderCLIOptions {
  app?: boolean;
}

export type CLIBuildOptions = BuildEnvironmentOptions & BuilderCLIOptions & GlobalCLIOptions;
export type CLIServeOptions = Omit<ServerOptions, 'https'> & GlobalCLIOptions & ServeCommandCLIOptions;
export type CLIPreviewOptions = PreviewCommandCLIOptions & GlobalCLIOptions & ServeCommandCLIOptions;
