import {
  ConfigEnv,
  defineConfig as viteDefineConfig,
  UserConfig,
  UserConfigExport,
  UserConfigFn,
  UserConfigFnObject,
  UserConfigFnPromise,
  Plugin,
} from 'vite';
import path from 'path';
import getAppInfo from '../utils/getAppInfo';
import configFileNames from './configFileNames';
import { configureDtsPlugin } from '../plugins/generateDts';

const CONFIG_MARKER = Symbol.for('MicroTSM-CLI.defineConfig');

export function isDefinedWithDefineConfig(config: UserConfig | undefined): boolean {
  return !!config && !!(config as any)[CONFIG_MARKER];
}

/**
 * Custom `defineConfig` wrapper for `@microtsm/cli`.
 *
 * This function wraps Vite's native `defineConfig`, providing automatic enhancements
 * tailored for MicroApp development using `single-spa`.
 *
 * 🔧 Features:
 * - Extends user-supplied Vite config with:
 *   - `__APP_NAME__` global define from `package.json` name
 *   - Auto-enabled `manifest` output
 *   - Static output naming conventions for `entryFileNames` and `chunkFileNames`
 *   - Default Rollup `input` fallback (`src/main.ts`)
 * - Injects useful external dependencies for MicroFrontend (`vue`, `vue-router`, etc.)
 * - Adds HTTPS support using local certificates (via `@vitejs/plugin-basic-ssl`)
 * - Forces ESM format output with hashed chunks
 *
 * 🚫 Limitations:
 * - Certain Vite options like `build.manifest`, `rollupOptions.output`, or `external` may be overwritten
 * - Not intended for generic use — this wrapper is opinionated for single-spa architecture
 * - HTTPS certificate paths are currently hardcoded; consider making them configurable
 *
 * 📦 Supported config formats:
 * - Object config: `defineConfig({...})`
 * - Promise config: `defineConfig(async () => ({...}))`
 * - Function config with env: `defineConfig((env) => ({...}))`
 *
 * 🧪 Example:
 * ```ts
 * import { defineConfig } from "@microtsm/cli";
 *
 * export default defineConfig(({ mode }) => ({
 *   plugins: [],
 *   define: {
 *     __FEATURE_FLAG__: JSON.stringify(true)
 *   },
 * }));
 * ```
 *
 * @param config - User's Vite config object, function, or promise
 * @returns Transformed Vite config with single-spa-specific enhancements
 */
export default function defineConfig(config: UserConfig): UserConfig;
export default function defineConfig(config: Promise<UserConfig>): Promise<UserConfig>;
export default function defineConfig(config: UserConfigFnObject): UserConfigFnObject;
export default function defineConfig(config: UserConfigFnPromise): UserConfigFnPromise;
export default function defineConfig(config: UserConfigFn): UserConfigFn;
export default function defineConfig(userConfig: UserConfigExport): UserConfigExport {
  const { name, version } = getAppInfo();
  process.env.__APP_NAME__ = name;
  process.env.__APP_VERSION__ = version;

  const generateConfig = (config: UserConfig): UserConfig => {
    const { external } = config.build?.rollupOptions ?? {};
    const libFormatsSpecified = typeof config.build?.lib === 'object' && config.build?.lib.formats?.length;
    const libFileNameSpecified = 'fileName' in (config.build?.lib || {});

    const builtConfig = viteDefineConfig({
      ...config,
      define: { ...config.define, __APP_NAME__: JSON.stringify(name) },
      build: {
        target: ['chrome64', 'firefox67', 'safari11.1', 'edge79'], // Minimum browser versions with native ES Modules support (see https://vite.dev/guide/build.html#browser-compatibility)
        manifest: 'manifest.json',
        sourcemap: false,
        ...config.build,
        lib: {
          entry: './src/main.ts',
          formats: ['es'],
          ...(config.build?.lib ?? {}),
        },
        rollupOptions: {
          ...(config.build?.rollupOptions || {}),
          input:
            config.build?.rollupOptions?.input ||
            (typeof config.build?.lib === 'object' && 'entry' in config.build?.lib && config.build?.lib?.entry) ||
            path.resolve('src/main.ts'),
          output: {
            format: libFormatsSpecified ? undefined : 'es',
            ...(libFileNameSpecified
              ? {}
              : {
                  entryFileNames: 'js/app.js',
                  chunkFileNames: 'js/chunk-[hash].js',
                }),
            ...(config.build?.rollupOptions?.output ?? {}),
          },
          external:
            !external || Array.isArray(external)
              ? [
                  'axios',
                  'microtsm',
                  /@microtsm\/(.*)/,
                  ...(external || []),
                  ...configFileNames, // Exclude the config file from being bundle by rollup
                ]
              : external,
        },
      },
    });

    const dtsPlugin = config.plugins?.find((p) => (p as Plugin<any>)?.name === 'microtsm:dts');

    if (dtsPlugin && 'pluginOptions' in dtsPlugin) {
      configureDtsPlugin(builtConfig, dtsPlugin.pluginOptions as any);
    }

    // To mark the config as being generated by this function
    Object.defineProperty(builtConfig, CONFIG_MARKER, { value: true });

    return builtConfig;
  };

  if (typeof userConfig === 'function') {
    return ((env: ConfigEnv) => {
      const result = userConfig(env);
      return result instanceof Promise ? result.then(generateConfig) : generateConfig(result);
    }) as UserConfigFn;
  }

  if (userConfig instanceof Promise) {
    return userConfig.then(generateConfig);
  }

  return generateConfig(userConfig);
}
